### ISSUE TITLE
ppt table of contents

### ISSUE THREAD

**Issue by alexhli** [davidgohel/ReporteRs#193]
Is there a way to create a table of contents in powerpoint with working links to other slides within the presentation?  Either linked by slide name or slide number is fine.  Thanks

**Comment by DianeBeldame** [comment]
Such a feature doesn't exist in PowerPoint, consequently it's not available
in ReporteRs. Sorry...

Le 26 avr. 2017 19:46, "alexhli" <notifications@github.com> a écrit :

Is there a way to create a table of contents in powerpoint with working
links to other slides within the presentation? Either linked by slide name
or slide number is fine. Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/davidgohel/ReporteRs/issues/193>, or mute the thread

**Comment by alexhli** [comment]
Thanks for the fast reply!  Within PowerPoint 2016, right clicking text or a shape brings up the option to add a hyperlink to either (1) web page or file, (2) this document or (3) email address.  Using this feature with option 2 should allow the user to manually create a TOC if they know the layout of the presentation.  Is it possible to insert hyperlinks in this way using R code?

**Comment by davidgohel** [comment]
You can only add external links: http://davidgohel.github.io/ReporteRs/articles/pot.html#hyperlink

For internal link, use package `officer` instead: 
https://davidgohel.github.io/officer/reference/ph_slidelink.html

**Comment by alexhli** [comment]
It looks like officer + ReporteRs could work, I will try that.  Thanks again for your response
