### ISSUE TITLE
Problem adding plots on RStudio server

### ISSUE THREAD

**Issue by ElenaDatak** [davidgohel/ReporteRs#86]
Hi David, 

I create an automated docx report, it works perfectly. But when I try to add a plot (from ggplot), I get the following error : 
java.lang.InternalError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable. 

And when I have the XLConnect library loaded, the error is : 
java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11.XToolkit

Here is my session informations : 

> sessionInfo()
R version 3.1.1 (2014-07-10)
Platform: x86_64-unknown-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=fr_FR.UTF-8          LC_NUMERIC=C                  LC_TIME=fr_FR.UTF-8           LC_COLLATE=fr_FR.UTF-8        LC_MONETARY=fr_FR.UTF-8      
 [6] LC_MESSAGES=fr_FR.UTF-8       LC_PAPER=fr_FR.UTF-8          LC_NAME=fr_FR.UTF-8           LC_ADDRESS=fr_FR.UTF-8        LC_TELEPHONE=fr_FR.UTF-8     
[11] LC_MEASUREMENT=fr_FR.UTF-8    LC_IDENTIFICATION=fr_FR.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] XLConnect_0.2-9        XLConnectJars_0.2-9    ggplot2_1.0.0          ReporteRs_0.7.8        ReporteRsjars_0.0.2    XML_3.98-1.1           RSQLite_1.0.0         
 [8] DBI_0.3.1              DT_0.0.21              plyr_1.8.1            reshape2_1.4   
[15] RcppEigen_0.3.2.2.0    Rcpp_0.11.5            data.table_1.9.4       Matrix_1.1-4           RODBC_1.3-11           yaml_2.1.13           
[22] haven_0.2.0            xlsx_0.5.7             xlsxjars_0.6.1         rJava_0.9-6            rCharts_0.4.5         
[29] shinythemes_1.0        htmltools_0.2.6        Cairo_1.5-6            shiny_0.11.1          

loaded via a namespace (and not attached):
 [1] base64enc_0.1-2   chron_2.3-45      colorspace_1.2-4  digest_0.6.4      grid_3.1.1        gtable_0.1.2      htmlwidgets_0.3.2 httpuv_1.3.2     
 [9] labeling_0.3      lattice_0.20-29   magrittr_1.5      MASS_7.3-35       mime_0.2          munsell_0.4.2     proto_0.3-10      R6_2.0           
[17] RCurl_1.95-4.3    RJSONIO_1.3-0     scales_0.2.5      stringr_0.6.2     tools_3.1.1       whisker_0.3-2     xtable_1.7-4     

Do you have any suggestion about this problem ?

Thanks,
Elena

**Comment by ttuti** [comment]
Are you by any chance working from a headless server?

**Comment by ElenaDatak** [comment]
Yes !

**Comment by davidgohel** [comment]
Hi Elena,

Your issue looks the same than the one of another user: https://groups.google.com/forum/#!topic/reporters-package/lsvUVJsCBaE

Unfortunately, I cannot reproduce the error. I have tested it on a centos 7 VM, the machine has no graphical environment and I am using ssh to run R with this machine. 

Can you give me more details about your platform, e.g. distribution of Linux, the version, anything that could help me to reproduce the system you're running?

KR
David

**Comment by davidgohel** [comment]
... I didn't notice the `RStudio server`. 
Are you running R with RStudio?

**Comment by ElenaDatak** [comment]
I've just tried the same code but on a shiny server into a shiny app : it works !

And yes, RStudio server

**Comment by ttuti** [comment]
The error on X11 is due to RStudio server being unable to pick $DISPLAY variable automatically from a headless Ubuntu Server installation. To fix it:
1.	Create an upstart script for xvfb. This creates a virtual display that mimics a GUI. Make sure the screen and display number on XVFBARGS are both 0 as then it remits the display at default screen (& apps by default pick 0).
2.	Create a system wide environment variable for $DISPLAY as 0
3.	Make sure ssh_config’s Forwading is enabled as well as sshd_config’s.
4.	Restart the server.

Here is my xvfb code:

--------------------------------------------------------------------------------------------------------------------
### BEGIN INIT INFO
# Provides: Xvfb
# Required-Start: $local_fs $remote_fs
# Required-Stop:
# X-Start-Before:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Loads X Virtual Frame Buffer
### END INIT INFO

XVFB=/usr/bin/Xvfb
XVFBARGS=":0 -screen 0 1024x768x24 -ac +extension RANDR +render -noreset"
PIDFILE=/var/run/xvfb.pid
case "$1" in
  start)
    echo -n "Starting virtual X frame buffer: Xvfb"
    start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile --background --exec $XVFB -- $XVFBARGS
    echo "."
    ;;
  stop)
    echo -n "Stopping virtual X frame buffer: Xvfb"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    echo "."
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
        echo "Usage: /etc/init.d/xvfb {start|stop|restart}"
        exit 1
esac

exit 0
------------------------------------------------------------------------------------------------------------------------------


This worked for me.

**Comment by ttuti** [comment]
The error on X11 is due to applications being unable to pick $DISPLAY variable automatically from a headless Ubuntu Server installation. To fix it (if you are using Ubuntu server):
1.	Create an upstart script for xvfb. This creates a virtual display that mimics a GUI. Make sure the screen and display number on XVFBARGS are both 0 as then it remits the display at default screen (& apps by default pick 0).
2.	Create an environment variable for $DISPLAY as 0
3.	Make sure ssh_config’s Forwading is enabled as well as sshd_config’s.
4.	Restart the server.
 

### BEGIN INIT INFO
 # Provides: Xvfb
 # Required-Start: $local_fs $remote_fs
 # Required-Stop:
 # X-Start-Before:
 # Default-Start: 2 3 4 5
 # Default-Stop: 0 1 6
 # Short-Description: Loads X Virtual Frame Buffer
 ### END INIT INFO

XVFB=/usr/bin/Xvfb
XVFBARGS=":0 -screen 0 1024x768x24 -ac +extension RANDR +render -noreset"
PIDFILE=/var/run/xvfb.pid
case "$1" in
  start)
    echo -n "Starting virtual X frame buffer: Xvfb"
    start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile --background --exec $XVFB -- $XVFBARGS
    echo "."
    ;;
  stop)
    echo -n "Stopping virtual X frame buffer: Xvfb"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    echo "."
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
        echo "Usage: /etc/init.d/xvfb {start|stop|restart}"
        exit 1
esac

  exit 0

---------------------------------------------------------------------------------------------
This worked for me.

**Comment by ttuti** [comment]
The code above is for Ubuntu 12.04  LTS 64-bit headless server

**Comment by ElenaDatak** [comment]
Thank you for your response. Since I'm not into server stuffs, it seems complicated to me to try your solution, but I will talk with an IT expert and let you know about it !

**Comment by davidgohel** [comment]
Elena

I am able to reproduce the issue. I think I solved it but I still don't understand what Rstudio is doing.
Can you update the package from github and tell me if it is ok?

David

**Comment by ElenaDatak** [comment]
I have a new error : java.lang.NoSuchMethodError: <init>

**Comment by davidgohel** [comment]
Did you install the package from a new clean R session?

**Comment by ElenaDatak** [comment]
Yes... And sorry, the entire error message is : 

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/lib64/RRO-8.0/R-3.1.1/lib64/R/library/ReporteRsjars/java/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/salettee/R/x86_64-unknown-linux-gnu-library/3.1/ReporteRsjars/java/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Error in .jnew(class.tables.CellProperties, .jborderProperties(robject$border.bottom),  : 
  java.lang.NoSuchMethodError: <init>

**Comment by davidgohel** [comment]
From what I can read, you installed ReporteRs in 2 different locations:

* /usr/lib64/RRO-8.0/R-3.1.1/lib64/R/library
* /home/salettee/R/x86_64-unknown-linux-gnu-library/3.1

**Comment by ElenaDatak** [comment]
Oops sorry, 
it works PERFECTLY now, thank you David :)

Have a nice weekend

**Comment by davidgohel** [comment]
Great!

have a nice WE too

David
