### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 1beb** [davidgohel/ReporteRs#97]
Is there any plan to go from Markdown to PowerPoint? I've looked into some basic regex to convert markdown to your wrapped code, but haven't had much success.

**Comment by davidgohel** [comment]
It already exists but it's not a perfect markdown. Plus there are restrictions because pptx shapes can't mix text, tables and graph/images. 

See 

    ?addMarkdown.pptx
    
Also to understand pptx restrictions with md, run 

    example("addMarkdown.pptx") 
    warnings()

There are plans but I don't have many times for ReporteRs actually, so it will be slow. Priority will be on migrating from java to Rcpp if possible.
